### ISSUE TITLE
Gulpタスクの配置についての提案

### ISSUE THREAD

**Issue by mitsuruog** [Horyuji/horyuji#10]
`gulp`以下のフォルダ構成についての提案です。

現状、次のようになっており、`tasks`配下にgulpタスク（ライブラリごとに分割）が収まっている構成です。

```
gulp/
  gulp.config.js
  tasks/
```

最近は次の理由で、ライブラリごとに分割したファイル構成より、ある一定の処理単位でまとめた方がいいと感じてます。
- ファイルが分散すると、gulpタスクの全体像が見えにくくなる
- 各ライブラリの設定はconfigで設定する方式の方が、利用者視点でカスタマイズがし易い

また、gulpのタスクには次の2つ属性が含まれており、これらがフラットなフォルダに存在すると、これはまた見通しが悪いと感じています。
- タスクの起点となるAction（trigger）
  - build、test、default（「〜したい」の部分）
- タスクの起点となるResourceの塊
  - js、css、html、image（「〜を」の部分）

その上で、新horyujiでは次のフォルダ構成を提案したいと考えています。

```
gulp/
  config.js
  actions/  （タスクのフロー「〜したい」の部分）
    build.js
    test.js
    ....
  tasks/      （実際のタスク「〜を」の部分）
    javascript.js
    style.js
    html.js
    ....
```

このようにすることで、タスクのフローと、実際のタスクの部分をフォルダで見分けることができ、さたに見通しがよくなると思います。

いかがでしょうか？

**Comment by MSakamaki** [comment]
@mitsuruog 
gulpのヘルプとかはどうして居ます？
自分は好みのgulpヘルプがないのでhoryujiに作っちゃってますが。

**Comment by mitsuruog** [comment]
gulp-discription使っても構わないです。
ただ、ここでの議論は「Gulpタスクの配置」についてです。
gulp-discriptionを使った場合、設定系はjsonで外出しできると思っているので、あまりこの議論によって影響される部分ではないかと。

> 自分は好みのgulpヘルプがないのでhoryujiに作っちゃってますが。

好みかどうかはわからないですが、
gulp4以降は`gulp.tree`でタスクの一覧が取得できるので、gulpのエコシステムを使うのも検討するべきですね。

http://blog.yudppp.com/gulp-v4/

**Comment by MSakamaki** [comment]
フォルダ構成

> また、gulpのタスクには次の2つ属性が含まれており、これらがフラットなフォルダに存在すると、これはまた見通しが悪いと感じています。

めっちゃ同意見で、自分も２つに分けてます。
自分はこうしてますね。

名前が微妙かも

``` sh

gulp/
  + env.js // 環境変数まわり
  + commands
    + ~したい部分、処理が必要となる部分、`gulp xxx`で実行される奴ら
  + plugins
    + 生gulpコマンドかつ単一処理が多い、設定のため置いてる、`gulp xxx`しない
```

> gulp4以降はgulp.treeでタスクの一覧が取得できるので、gulpのエコシステムを使うのも検討するべきですね。

gulp-discriptionはgulpV4を意識して作ってあるので、そこは後に必要なら変更できる前提で作ってあります。
（ただ、今動くんで問題ない的なので手入れて無い感じで）

**Comment by mitsuruog** [comment]
今回babelを利用する想定であることもあって、gulpタスク間の非同期処理が辛い（babalが完了してから後続タスクを実行するとか）との話があり、ひとまずフラットな形にします。

参考）
gulp 3.5でgulp.runがdeprecatedになりました | Web Scratch 
http://efcl.info/2014/0125/res3630/

gulp4から`parallel`と`series`がサポートされるので、しばらく様子見します。
https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#gulpparalleltasks

```
gulp/
  config.js
  tasks/
    default.js
    serve.js
```
