### ISSUE TITLE
Develop Task

### ISSUE THREAD

**Issue by MSakamaki** [Horyuji/horyuji#16]
- livereload
  - [x] browserSync
- compile
  -  babel (javascript) #25
  - [x] css 
- lint
  -  jscs (javascript) #25
  -  eslint (javascript) #25
  - [x] css
  - [x] HTMLHint (html)
- watch
  - [x] javascript
  - [x] css
  - ~~html~~
  - [x] test [want]

**Comment by mitsuruog** [comment]
- watch
  -  javascript
  - css
  - html
  - test [want]

**Comment by MSakamaki** [comment]
@mitsuruog 
タスクをトップに引っ越しました

**Comment by mitsuruog** [comment]
周辺からやりますｗ。watchのhtml行きますね。

**Comment by mitsuruog** [comment]
js周り行きますねー

**Comment by MSakamaki** [comment]
依存性のチェックまわりのCI追加しますね。

**Comment by MSakamaki** [comment]
@mitsuruog 
js関連のタスクはそれだけで複雑化しそうなので別チケットにしました
#25

**Comment by MSakamaki** [comment]
test done.
