### ISSUE TITLE
Testing Tasks

### ISSUE THREAD

**Issue by MSakamaki** [Horyuji/horyuji#17]
# framework and runner
- jasmine 2.x
- karma
# task
- unit test
  - [x] karma.config 
  - [x] karma (travis)
  - report
    - [x] covorage
    - [ ] metrics
- e2e test
  - other repository...

**Comment by mitsuruog** [comment]
:+1:

**Comment by mitsuruog** [comment]
途中までやりますね。

**Comment by MSakamaki** [comment]
お願いします！

**Comment by MSakamaki** [comment]
metrics回り取りかかりますね。

**Comment by MSakamaki** [comment]
metricsは外だし
