### ISSUE TITLE
javascript build tasks

### ISSUE THREAD

**Issue by MSakamaki** [Horyuji/horyuji#25]
javascriptビルドだけ別タスクに
1. lint 
   - [x] jscs
     - [x] 開発時はfixしない
     - [x] テスト時はfixしない
     - [x]  build時はfixしない
   - [x] eslint
2. build
   - [x] babel compile
   - [x] map
3.  uglify (minify)
   - [x] 開発時は行わない
   - [x] テスト時は行わない
   - [x]  build時は行う
4.  concat(結合)
   - [x] 開発時は行わない
   - [x] テスト時は行わない
   - [x]  build時は行う

**Comment by MSakamaki** [comment]
@mitsuruog 
gulp自体の`jscs`や`eslint`チェックはどのタイミングでどう組み込むのが理想ですかね・・・？

**Comment by mitsuruog** [comment]
> gulp自体のjscsやeslintチェックはどのタイミングでどう組み込むのが理想ですかね・・・？

devとbuildの最初がいいんじゃじゃないかなー

**Comment by MSakamaki** [comment]
`console.log`使うとworningでますね・・・
後で除去しといた方が良いですか？

**Comment by mitsuruog** [comment]
どうしても出したいなら`gulp-util`を使いましょう。

**Comment by mitsuruog** [comment]
> console.log使うとworningでますね・・・

これ、下の件ですね、勘違いしてましたすみません。

プロダクションコードにconsole.logは含めるかどうか · Issue #33
