### ISSUE TITLE
protractor 3.0についてのメモとお話の場

### ISSUE THREAD

**Issue by MSakamaki** [Horyuji/horyuji#27]
個人的にメモ
https://github.com/angular/protractor/blob/master/CHANGELOG.md

**Comment by mitsuruog** [comment]
大きなトピックとしては
- Jasmine > 2
- Node > 4.2

でしょうか。個人的に気になるのが
- Add BrowserStack support.
- Add protractor.prototype.restart

ですかね。restartは認証のテストとかで使うと良さそうに見えます。
（とはいえ、最近protractor触れるようなお仕事してないのでほとんど独り言ですが。。。）

**Comment by mitsuruog** [comment]
別プロジェクトにするのでクローズします
