### ISSUE TITLE
babel-core/registerをどうにかしてパフォーマンス改善したい

### ISSUE THREAD

**Issue by mitsuruog** [Horyuji/horyuji#35]
gulpタスク開始時に必ず次のようになって、待たされて「うっ。。。」となるので、可能であれば改善していきたいです。

```
Requiring external module babel-core/register
```

**Comment by MSakamaki** [comment]
これって初回ロードの時のみの問題でlivereload開発とかはあまり速度変わらないんですよね？
babel-core使ってやる分にはまだ回避出来ない問題かも・・・
ちなみにnode  v5.x系だとそこそこ早い気がします。

**Comment by mitsuruog** [comment]
> これって初回ロードの時のみの問題でlivereload開発とかはあまり速度変わらないんですよね？

そうです。初回のみです。
nodeは4.2なのですが、私のマシンが貧弱なMBAなのが問題なのかも。
MUSTな要求ではないので、ひとまず塩漬けでもいいです。

**Comment by mitsuruog** [comment]
初回起動時のみ気になる問題ですのでひとまずクローズします。
