### ISSUE TITLE
ノウハウと課題

### ISSUE THREAD

**Issue by MSakamaki** [Horyuji/horyuji#9]
纏めようと思う。

参考
https://github.com/mitsuruog/frontend-stone-walls/tree/develop

**Comment by MSakamaki** [comment]
~~アルコール駆動で~~なぐりがき

### 個人的な観点で、問題なさそうな物とかノウハウとか
- フレームワーク
  - アプリ
    - なんでもいい、どっちかと言うと設計重要
  - テスト
    - なんだかんだ言ってprotractorは初期導入楽、でも闇多い、エコ多い
      - protractor + node-canvas、癖があるけど使いこなせるとe2eに無限の可能性広がる
    - nightwatchjs、シンプルにシナリオ書けるのは良いけど、設定面倒で、エコシステム不十分、でもシンプルなフレームワークなのでprotractorと違って機能のコントロールしやすい
  - タスク
    - 信頼できる人とgulpでやるのいいよね
    - メンバーにフロント開発のビルドプロセスが理解できていて、Gulp詳しい人居るならGulpで
    - ~~ノリと勢いだけ~~フロントのビルドが理解できてないメンバーばっかだとGruntで
  - 開発サーバー（livereload)
    - webpack
      - 高機能だけど、他のコンポーネントと役割被る、でかすぎ
    - browserify
      - シンプルだけど、まだちょっと大きいかな・・・
    - browsersync
      - もはや愛、ぴったりフィット
    - koa, express, hapi
      - 無限の可能性を秘めてる、個人的にはコレでやってたりする、でも仕事だと使わない
  - モック
    - koa, express, hapi
      - express > koa > hapi みたいな感じ、基本コッチ使う
    - nock
      - 機能がめっちゃ少ないと使う、複雑なときはexpressとかに置き換える。
- e2eテスト管理はリポジトリ内に置くより別リポジトリにした方が良かった
  - 前提としてあらゆるチーム(フロント以外)が割とe2e作ったりメンテしたりする事を目的に
- デザインガイド重要
  - sass Doc的なのの導入
  - グランドデザインコンセプトとの棲み分けと管理が大事
- mockは外側からコントロール可能にしとくとe2eテストが凄い楽
  - 自分の答えとして[vantageJS](https://github.com/dthree/vantage)を使用、でも別にWebSocketとかデータ書き換えようにAPI切っても問題ない、vantageJS使う理由は「API」「コード中」「コンソール」それぞれからアクセスが可能であるため、取り回ししやすいから。
- AltJS
  - TypeScript
    - かなり好き、でもカフェイン中毒者と良くバトる、エンプラ向きだとおもう、あとVsCodeエディタが来たので自分の中でフロント開発するときの最強設定
  - Flow
    - 結構すき、メンバーが環境構築でハマったりする、でもTypeScriptがあるからTypeScript使う
  - babel
    - 割と好き、TypeScriptが使えない場合はコレ使う、ES5よりエンプラ向き
  - 生JS
    - エンプラ向きじゃない言語だよね・・・
  - CoffeeScript
    - ~~カフェイン中毒者め・・・・~~、エンプラ~~でコレを使う意味が良くわからない~~にはあまり向いてない気がする、個人で使う分には良いツール。

### 課題とか 迷いとか
- JSパッケージ管理、bowerかぁ・・・・bowerしかないよね・・・
  - ~~JSPMがディスられて辛い~~
- cssプリプロセッサとPostCSS
- NavigationTime Apiあたりもうちっと便利なライブラリつくりたい
- first view
- lint系
  - 個人的にはeslint + xo 使いたい
  - でもエンプラ的にはjscsの方が良い気がする。
  - PJメんバーのエディタをフリーダムにすると、エディタとタスクランナーのlint管理が微妙にめんどい

### メモ
- 12月頭にある[JSConf](http://lastcall.jsconf.us/schedule.html)で面白い物出るとイイナ！

**Comment by mitsuruog** [comment]
テストの件はunitとe2eで分けて考えたいですね。

## Unit

テストランナーとアサーションあたりをどうするか決める必要がありますね。
個人的にはkarma+jasmin>2.0を使ってて、power-assertもっと使ってみたいです。
とはいえ、Javaのspockが気に入ってて、同様のテストフレームワークがjsに存在しないか探しています。

Unitテスト系のタスクに求めたいものは次の通りです。
- [ ] [MUST]テストの実行
- [ ] [MUST]テスト結果の表示
- [ ] [MUST]テストカバレッジの集計
- [ ] [WANT]`bower install`した時にkarma.confに依存関係追加（karmaで行くのであれば）
- [ ] [WANT]テスト結果の通知（webhookなど、gulp-notifyでOK） 

MUSTの部分は現在のhoryujiで実現できているはず

## E2E

> e2eテスト管理はリポジトリ内に置くより別リポジトリにした方が良かった
> 前提としてあらゆるチーム(フロント以外)が割とe2e作ったりメンテしたりする事を目的に

確かに、そういう意味では別にした方が良さそうですね。
horyujiとは切り離すことでOKです。

protractor + node-canvas、nightwatchjsは触ったことないのですが、基本的にprotractorベースで実績など十分かなと思ってます。
ひとまず候補に入れておいて、e2eのところで別途議論しましょ。

**Comment by mitsuruog** [comment]
開発サーバー（livereload)の件は`browsersync`でいいでしょ。私も愛しか感じないです。

モックに関しては[CyberAgent/node-easymock](https://github.com/CyberAgent/node-easymock)を使ってます。
、、、が、最近はswaggerエコシステムとの連携を考えないとなーと感じています。

モックに感しては、リソース限られてるので、今のところ[WANT]かなと考えてます

**Comment by mitsuruog** [comment]
> デザインガイド重要

うーん、割りとデザイナ会社からのHTMLを組み込んでいる身としては[WANT]ですかね。
（ここデザイナ側の力量や意識に大きく依存するので）

本当はCSS系のタスクに組み込みたいです。
おそらくデザイナ側の理解を得るためにも、自動化した上で早くFBサイクルを回せる環境は必要だと考えています。
最近、面白いの見つけたので、いくつか候補を持ち寄って選択したです。
[jonathantneal/mdcss](https://github.com/jonathantneal/mdcss)

**Comment by mitsuruog** [comment]
AltJSについては（学習して今後潰しが効くという意味で）本当に悩ましいですね。

標準という意味ではvanillajsかbabelだと思います。個人的にはbabel押しです。

**Comment by mitsuruog** [comment]
「課題とか 迷いとか」の自分なりの意見

> JSパッケージ管理、bowerかぁ・・・・bowerしかないよね・・・

ここ一年くらいはbowerでいいんじゃないかな。

> cssプリプロセッサとPostCSS

jsがbabelのエコシステムに統合されてきたのと同じ流れで、cssはPostCSSのエコシステムに統合される流れが起きそうですね。
PostCSSはhoryujiに取り込んでおいて、徐々にpluginを追加していきたいと思います。

> NavigationTime Apiあたりもうちっと便利なライブラリつくりたい
> first view

確かに本番デプロイする前にパフォーマンス系の問題わかるといいですね。
e2eと組み合わせれば有効に機能しそうな気がしています。

> lint系

個人的にはeslintとjscsは必要。
初期設定が面倒なのでairbnbのルールを拡張しています。

> PJメんバーのエディタをフリーダムにすると、エディタとタスクランナーのlint管理が微妙にめんどい

ここ凄いわかるんですが、プロジェクトのトップに1つ`~rc`を置くようにすると割と平和な気がしています。
productionとtestで違うとエディタと喧嘩する気がします。悩ましいですね。

**Comment by mitsuruog** [comment]
長々書きましたが、やりたいことは次の通りです。
- 本当の現場で使えるようにhoryujiの全体構成を見直したい（新horyuji）
  - horyujiが提供するタスクをカテゴリ分けして、それぞれのカテゴリごとに目的と価値を決めたい（グランドデザイン）
  - 目的と価値を決めた上で、いくつかの選択肢（サードパーティ製、内製）から実現方式を選択したい
  - あくまで、えんぷらターゲット
  - できれば勉強会など普及活動

まず、新horyujiのグランドデザインを決めたいですね。

**Comment by MSakamaki** [comment]
> power-assert

個人的には反対派  power-assertは実案件で使いましたが、あれ個人でやると便利ですが扱いが難しく玄人向けの印象を受けますここら辺に学習コストを無駄にかけたくないので、スキルの安定しないチームでやるには不向きかなと。
（学習コストかけるのならもっと別のところにかけたい）

> 同様のテストフレームワークがjsに存在しないか探しています。

無いなら作る！

> うーん、割りとデザイナ会社からのHTMLを組み込んでいる身としては[WANT]ですかね。
> （ここデザイナ側の力量や意識に大きく依存するので）

うちはsc5-styleguide+カスタマイズプラグイン追加してやってます。
居着くか候補の中から、これがプラガブル＆最適と判断して使ってます。
http://styleguide.sc5.io/

デザイナ側の力量と意識は確かにそうですね・・・
でもしてもらわないとボトルネックになるのでやってもらいました。
とくに大人数かつリモート開発や複数チームでやってるので、デザインガイドないとグダグダになっちゃうんですよね。

> 標準という意味ではvanillajsかbabelだと思います。個人的にはbabel押しです。

`traceur-compiler`も忘れて上げないでください・・・

> まず、新horyujiのグランドデザインを決めたいですね。

:+1:

**Comment by mitsuruog** [comment]
ひとまず頭出しできて、1.0に向け動き出せたのでクローズします。
